server: 
  port: 
    80
spring: 
  application:
    name: share-data-catch-consumer
  profiles:
    include:
      - swagger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'wk19930829'
    url: jdbc:mysql://106.13.47.54:3306/share?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
  rabbitmq:
    host: 172.16.5.2
    port: 5672
    username: admin
    password: admin123

feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
        loggerLevel: basic

test:
 name: wangkai