server: 
  port: 
    8081
spring: 
  application:
    name: share-data-catch-action
  profiles:
    include:
      - swagger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'wk19930829'
    url: jdbc:mysql://106.13.47.54:3306/share?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
  rabbitmq:
    virtual-host: my_vhost #如果没有虚拟主机则不需要配置，rabbitmq默认是没有的，这里添加了一个my_vhost
    host: 106.13.47.54
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true #开启 confirm 确认机制
    publisher-returns: true #开启 return 确认机制
    template:
      mandatory: true #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
  redis:
    host: 106.13.47.54
    port: 6379
    database: 0
    timeout: 50000
    password: 123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最小空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接超时时间（毫秒）
        timeout: 50000
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
        loggerLevel: basic
#设置日志级别
logging:
  level: 
    com.alibaba.nacos.client.naming: 
      error
      
getValueFromNacos:
  appName: 
    share-data-catch-consumer